Repository Flexberry/Flexberry.AndroidODataOffline.Sample, pull requests merged in 2023-05, with the labels that each got.

#2 Добавлены представления для объектов
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/enums/VoteType.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/AppData.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/ApplicationUser.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Vote.kt
Labels: enhancement

#3 Добавлена сборка APK в ghActions
  src/AndroidODataOfflineSample/.github/workflows/build_apk.yml
Labels: enhancement

#5 Онлайн модель объектов ApplicationUser и Vote.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkApplicationUser.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkVote.kt
Labels: enhancement

#11 DataService.
  src/AndroidODataOfflineSample/app/build.gradle
  src/AndroidODataOfflineSample/app/src/main/AndroidManifest.xml
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/MainActivity.kt
Labels: invalid

#14 Odata DataSource.
  src/AndroidODataOfflineSample/app/build.gradle
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/OdataTest.kt
  src/AndroidODataOfflineSample/app/src/main/AndroidManifest.xml
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/ApplicationUserOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/OdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/VoteOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkApplicationUser.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkVote.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/query/Filter.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/query/FilterType.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/query/OrderType.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/query/QuerySettings.kt
Labels: enhancement

#17 doc: querysettings.
  docs/Настройки запросов QuerySettings.md
Labels: documentation

#18 doc: Документация по DI Hilt (внедрение ViewModel)
  docs/Внедрение зависимостей с помощью Hilt.md
Labels: documentation

#19 doc: OdataDataSource.
  docs/Источник данных OData.md
Labels: documentation

#27 Odata url перенесен в конфиг билда
  src/AndroidODataOfflineSample/app/build.gradle
Labels: enhancement

#26 Документация по Jetpack Compose
  docs/Jetpack Compose.md
  docs/images/PreviewMode.jpg
Labels: documentation

#28 Обновить документацию по odata.
  docs/Источник данных OData.md
Labels: documentation

#29 Преобразование Network-модели в общую.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/ApplicationUserRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/VoteRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/ApplicationUser.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Vote.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceCommon.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/applicationuserlistformmodel/ApplicationUserListFormModelScreen.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/votelistformmodel/VoteListFormModelScreen.kt
Labels: enhancement

#31 Хитрые тесты на создание, обновление, удаление объектов в OData.
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/OdataCommonTest.kt
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/OdataTest.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceCommon.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkApplicationUser.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkVote.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/query/Filter.kt
Labels: wontfix

#32 Синхронизатор данных.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/ApplicationUserRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/VoteRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/ApplicationUser.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Vote.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/sycnhonization/SynchronizationService.kt
Labels: enhancement

#37 Добавление сущностей Detail и Master тестового стенда Odata.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/DetailRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/MasterRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Detail.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Master.kt
Labels: enhancement

#38 Добавление Master и Detail в network.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/DetailOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/MasterOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceTypeManager.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkDetail.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkMaster.kt
Labels: enhancement

#39 Matser и Detail network. Преобразование в базовую сущность и обратно.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Detail.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Master.kt
Labels: enhancement

#40 DI и тесты для Master и Detail network.
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/OdataCommonTest.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/DetailRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/MasterRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/di/DataSourceModule.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/sycnhonization/SynchronizationService.kt
Labels: enhancement

#46 Matser и Detail local. Преобразование в базовую сущность и обратно.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/entities/MasterEntity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Detail.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Master.kt
Labels: enhancement

#47 DI и тесты для Master и Detail local.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/DetailRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/MasterRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/di/DataSourceModule.kt
Labels: enhancement

#49 Загрузка детейлов вместе с загрузкой мастера. Network.
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/OdataTest.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/DetailOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/MasterOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceCommon.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/interfaces/NetworkDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkApplicationUser.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkDetail.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkMaster.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkVote.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/query/View.kt
Labels: enhancement

#52 Загрузка детейлов вместе с загрузкой мастера. Local.
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/RoomTest.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/DetailRoomDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/MasterRoomDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/room/RoomDataBaseEntityInfo.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/room/RoomDataBaseManager.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/room/RoomDataBaseRelation.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/room/RoomDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/room/RoomDataSourceCommon.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/entities/AppDataEntity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/entities/DetailEntity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/entities/MasterEntity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/interfaces/LocalDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/DetailOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/MasterOdataDataSource.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceCommon.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceTypeManager.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/query/View.kt
Labels: enhancement

#53 Загрузка данных MasterListForm.
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/OdataCommonTest.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/MainActivity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/MasterListFormActivity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/MasterRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/di/StateModule.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceCommon.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/datasource/odata/OdataDataSourceTypeManager.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkDetail.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/network/models/NetworkMaster.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/masterlistformmodel/MasterListFormScreen.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/masterlistformmodel/MasterListFormViewModel.kt
Labels: enhancement

#57 Добавление в документацию пункта про ThreadPolicy
  docs/Разрешить работу по сети и протоколу http.md
Labels: documentation

#58 Синхронизация.
  src/AndroidODataOfflineSample/app/src/androidTest/java/com/flexberry/androidodataofflinesample/RoomTest.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/MasterRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/local/datasource/room/RoomDataSourceCommon.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/synchonization/SynchronizationService.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mainmodel/MainViewModel.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/masterlistformmodel/MasterListFormViewModel.kt
Labels: enhancement, test

#55 Data load DetailListForm
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/DetailListFormActivity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/DetailRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/MasterRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/TestDataRoomRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/detaillistform/DetailListFormScreen.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/detaillistform/DetailListFormViewModel.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mainmodel/MainViewModel.kt
Labels: enhancement

#54 add master edit form
  docs/Навигация между формами.md.backup
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/MasterEditFormActivity.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/model/Master.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mastereditformmodel/MasterEditFormScreen.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mastereditformmodel/MasterEditFormViewModel.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/masterlistformmodel/MasterListFormScreen.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/masterlistformmodel/MasterListFormViewModel.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/navigation/BaseNavigation.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/navigation/Destination.kt
Labels: documentation, enhancement

#59 Master edit form.
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/data/MasterRepository.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mastereditformmodel/MasterEditFormScreen.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mastereditformmodel/MasterEditFormViewModel.kt
  src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/masterlistformmodel/MasterListFormViewModel.kt
Labels: enhancement
